before:
  hooks:
    - make clean deps

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w

dockers:
  - image_templates:
      - "ghcr.io/estahn/cloudping:latest-amd64"
      - "ghcr.io/estahn/cloudping:{{ .Version }}-amd64"
      - "ghcr.io/estahn/cloudping:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/estahn/cloudping:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/estahn/cloudping:{{ .Major }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/estahn/cloudping:latest-arm64v8"
      - "ghcr.io/estahn/cloudping:{{ .Version }}-arm64v8"
      - "ghcr.io/estahn/cloudping:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
      - "ghcr.io/estahn/cloudping:{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/estahn/cloudping:{{ .Major }}-arm64v8"
    use: buildx
    dockerfile: Dockerfile
    goarch: arm64
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--build-arg=VERSION={{.Version}}"
    - "--build-arg=BUILD_DATE={{.Date}}"
    - "--build-arg=VCS_REF={{.FullCommit}}"
    - "--platform=linux/arm64/v8"

brews:
  - name: cloudping
    tap:
      owner: estahn
      name: homebrew-tap

    folder: Formula
    homepage: https://github.com/estahn/cloudping
    description: "cloudping identifies the cloud provider regions geographically closest and returns them in order of lowest to highest latency."
